ALTER TABLE users ADD COLUMN name VARCHAR(255) NOT NULL;
ALTER TABLE users ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISABLED', 'PENDING'));
ALTER TABLE users ADD COLUMN last_login TIMESTAMP;

CREATE INDEX idx_users_status ON users(status);